### ISSUE TITLE
Object cache does not call wp_using_ext_object_cache

### ISSUE THREAD

**Issue by spacedmonkey** [10up/plugin-check#103]
### Describe the bug

The object cache file bootstrapped in, does not call `wp_using_ext_object_cache( false );`. Meaning WordPress will see that an external object cache is in use. 

### Steps to Reproduce

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by spacedmonkey** [comment]
@felixarntz Should this be applied on the performance plugin as well?

**Comment by felixarntz** [comment]
@spacedmonkey Can you explain this a bit more? Where in the core code do you mean that WordPress thinks an external object cache is used? When I look at `wp_start_object_cache()`, it loads the file, but then only sets `wp_using_ext_object_cache( true )` if the `wp_cache_init()` function now exists, which it doesn't in our case since the drop-in intentionally does not declare it.

**Comment by spacedmonkey** [comment]
> @spacedmonkey Can you explain this a bit more? Where in the core code do you mean that WordPress thinks an external object cache is used? When I look at `wp_start_object_cache()`, it loads the file, but then only sets `wp_using_ext_object_cache( true )` if the `wp_cache_init()` function now exists, which it doesn't in our case since the drop-in intentionally does not declare it.

Sorry, I thought that `wp_using_ext_object_cache( true )` was called if the file exists, didn't remember the cache_init part. This ticket is invalid.
