### ISSUE TITLE
Setup PHPMD in repo

### ISSUE THREAD

**Issue by spacedmonkey** [10up/plugin-check#106]
### Is your enhancement related to a problem? Please describe.

[PHPMD](https://phpmd.org/) is tool similar to Java's PMD.

PHPMD is a useful tool, for find overly complex code, unused code, code path that will never be reached and other issues. 

PHPMD, like phpstan can be introduced in the CL pipeline and can be seen as mark of quality if CI tests are passed. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by spacedmonkey** [comment]
I wonder if you could take a look into this @swissspidy

**Comment by swissspidy** [comment]
I the team is interested in using it and doing the necessary refactorings, sure.

Here are the top findings from PHPMD:

```
includes/CLI/Plugin_Check_Command.php:100                    NPathComplexity  The method check() has an NPath complexity of 10368. The configured NPath complexity threshold is 200.
includes/CLI/Plugin_Check_Command.php:272                    NPathComplexity  The method flatten_file_results() has an NPath complexity of 256. The configured NPath complexity threshold is 200.
includes/Checker/Checks/Enqueued_Scripts_Size_Check.php:170  NPathComplexity  The method check_url() has an NPath complexity of 291. The configured NPath complexity threshold is 200.
includes/Traits/URL_Aware.php:112                            NPathComplexity  The method go_to() has an NPath complexity of 1920. The configured NPath complexity threshold is 200.
```

NPath describes the number of possible code paths. The lower the better, as it makes testing and maintenance easier due to the reduced complexity. Often times this can be achieved by extracting parts of the logic into separate methods.
