### ISSUE TITLE
Implement plugin-updaters check

### ISSUE THREAD

**Issue by eclarke1** [10up/plugin-check#179]
### Is your enhancement related to a problem? Please describe.

https://github.com/WordPress/plugin-check/blob/trunk/checks/plugin-updaters.php (can be implemented using the new abstract base class from https://github.com/10up/plugin-check/pull/175 )

### Acceptance Criteria
- The `Plugin_Updater_Check` class should be created and located at `includes/Checker/Checks`.
- The `Plugin_Updater_Check` class should extend the `Abstract_File_Check` abstract class.
- The `look_for_update_uri_header()` method should be defined within the `Plugin_Updater_Check` class.
- The `look_for_update_uri_header()` method should retrieve the contents of the plugin's main file and extract the plugin headers using [get_plugin_data](https://developer.wordpress.org/reference/functions/get_plugin_data/) function.
- The `look_for_update_uri_header()` method should check if the UpdateURI header is present and has a value.
- If the UpdateURI header is not present, an error should be reported.
- The `look_for_updater_file()`, `look_for_plugin_updaters()` and `look_for_updater_routines()` method should be defined within the `Plugin_Updater_Check` class.
- The `look_for_updater_file()` method (based on [check_updaters()](https://github.com/WordPress/plugin-check/blob/trunk/checks/plugin-updaters.php#L17-L30)) should scan the plugin's files for `plugin-update-checker.php` file. 
- If that file found, an error should be reported.
- The `look_for_plugin_updaters()` method (based on [check_updaters()](https://github.com/WordPress/plugin-check/blob/trunk/checks/plugin-updaters.php#L32-L51)) should scan the plugin's files for any indications of plugin updaters being implemented. 
- If any plugin updater implementations are found, an error should be reported.
- The `look_for_updater_routines()` method (based on [check_updater_warnings()](https://github.com/WordPress/plugin-check/blob/trunk/checks/plugin-updaters.php#L54)) should scan the plugin's files for any indications of modifications to WordPress update routines.
- If any modifications to WordPress update routines are found, a warning should be reported.

### Test Coverage
- The `look_for_update_uri()` method should be tested to ensure it reports an error when the UpdateURI header is not present in the plugin header.
- The `look_for_updater_file()`, `look_for_plugin_updaters()` and `look_for_updater_routines()` methods should be tested to ensure they raise a error/warning when the plugin header does not have an UpdateURI and when there are indications of plugin updaters and WordPress update routines in the plugin's files.
- Test cases should cover scenarios where the UpdateURI header is missing, present but empty, and present with a valid value.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mukeshpanchal27** [comment]
@felixarntz @jjgrainger I've updated the AC's and this is ready for review. Thanks!

cc. @eclarke1

**Comment by felixarntz** [comment]
@mukeshpanchal27 A few points of feedback on the ACs:
> The `look_for_update_uri()` method should retrieve the contents of the plugin's main file and extract the plugin headers.

No need to manually retrieve the contents of the plugin's main file, you can use [`get_plugin_data()`](https://developer.wordpress.org/reference/functions/get_plugin_data/) instead. Nit-pick: Maybe rename the method to `look_for_update_uri_header()` to clarify what it does.

> The `look_for_updaters()` method should scan the plugin's main file for any indications of plugin updaters being implemented.

Why the plugin main file and not all plugin files? Can you clarify which part of https://github.com/WordPress/plugin-check/blob/trunk/checks/plugin-updaters.php this method should cover? Since we're reimplementing the approach from existing code, I think it would be helpful to mention those references specifically.

> The `look_for_updater_routines()` method should scan the plugin's main file for any indications of modifications to WordPress update routines.

Same feedback here, why only the plugin main file? And can you clarify what part of the code from the original https://github.com/WordPress/plugin-check/blob/trunk/checks/plugin-updaters.php this refers to?

FWIW, I would suggest to even create 2 separate functions for just the code that is in [this function](https://github.com/WordPress/plugin-check/blob/trunk/checks/plugin-updaters.php#L16) in the original code: It does two different things, so it would be better to have two methods.

**Comment by mukeshpanchal27** [comment]
Thanks @felixarntz, I have updated AC's as requested. Assigning back to you for review. cc. @jjgrainger

**Comment by felixarntz** [comment]
Thanks @mukeshpanchal27, ACs LGTM!
