### ISSUE TITLE
“%i” placeholder in $wpdb->prepare()

### ISSUE THREAD

**Issue by celtislab** [10up/plugin-check#287]
Using %i gives an error.

Unsupported placeholder used in $wpdb->prepare(). Found: “%i”

**Comment by r-martins** [comment]
Could you be clearer on explaining how to reproduce the issue?
Is it really related to plugin-ckeck or $wpdb core?

**Comment by celtislab** [comment]
$wpdb->prepare() should allow "%d", "%f", "%s", "%i" as placeholders.

https://developer.wordpress.org/reference/classes/wpdb/prepare/

However, when I use "%i", it shows as an unsupported placeholder.

![plugin-check-prepare-error](https://github.com/WordPress/plugin-check/assets/132246399/ce51907f-992b-46be-a332-a3efe81c266e)

This is probably caused by UNSUPPORTED_PLACEHOLDER_REGEX in the file below

/wp-content/plugins/plugin-check/vendor/wp-coding-standards/wpcs/WordPress/Sniffs/DB/PreparedSQLPlaceholdersSniff.php

line.99 and 114.
%%[dfFs] 

does not contain "%i"
I think you need to modify it to %%[dfFsi]

**Comment by r-martins** [comment]
Thank you very much for clarifying.
In this case, its related to [wp-coding-standards projetct](https://github.com/WordPress/WordPress-Coding-Standards), and [this is the file](https://github.com/WordPress/WordPress-Coding-Standards/blob/develop/WordPress/Sniffs/DB/PreparedSQLPlaceholdersSniff.php) that supposedly affects what you mentioned.

I believe it's already [reported there](https://github.com/WordPress/WordPress-Coding-Standards/issues/2079).

If this is the case, would you mind to close the issue here (and perhaps mention this thread there)?

Cheers

**Comment by celtislab** [comment]
I hope it will be fixed soon.
