### ISSUE TITLE
HTML tags in error messages unexpectedly escaped

### ISSUE THREAD

**Issue by swissspidy** [10up/plugin-check#312]
<img width="1546" alt="Screenshot 2023-10-30 at 21 35 35" src="https://github.com/WordPress/plugin-check/assets/841956/4791d7e0-dddf-468b-9abf-f33b42645e17">

The `<code>` tags shouldn't be escaped here.

**Comment by ernilambar** [comment]
@swissspidy I checked other messages also. No messages have HTML tags inside the string. To highlight some words apostrophe or double quotation is used.

Eg: `'$response'`
`The parameter "$term_args"`

May be we should also follow that convention for the message and avoid HTML tags inside the message string. Thoughts?

**Comment by swissspidy** [comment]
If no other messages use HTML tags in them, then removing them here sounds reasonable.

**Comment by ernilambar** [comment]
Related PR - https://github.com/WordPress/plugin-check/pull/352

**Comment by mukeshpanchal27** [comment]
In my opinion, it might be more beneficial to explore a solution that allows the utilization of HTML tags within the message. This approach could prevent encountering a similar situation in case any external checks introduce those tags again. Rather than removing them entirely, can we explore ways to incorporate and utilize HTML tags safely? cc. @felixarntz @joemcgill

**Comment by swissspidy** [comment]
Well an alternative is to use `wp_kses_post` to allow a specific set of tags, but then you need to remove those again for CLI context. And if you allow arbitrary HTML then that's unsafe and more cumbersome. Which is why #532 is just simpler for now.

If we wanna _properly_ support HTML tags that works in all contexts, a new issue is best for that.

**Comment by ernilambar** [comment]
Eventhough we allow HTML tag in browser, in CLI it would be not good to display HTML tag like this.
<img width="1270" alt="Screen Shot 2023-12-20 at 8 56 52 PM" src="https://github.com/WordPress/plugin-check/assets/2098823/c85cb863-d3e5-4ff0-9fe2-2ef806b36ea4">

**Comment by joemcgill** [comment]
Using late escaping principles, it would make sense to me that if HTML is being stored in messages that each output target would be responsible for its own escaping, so we could use `wp_kses` to define the subset of HTML that is supported in the admin, while CLI strips all tags.

**Comment by felixarntz** [comment]
I like the idea of using `wp_kses()` instead of `esc_html()`:
* For regular UI output, support a few basic inline tags (e.g. `a[href]`, `strong`, `em`, `code`, ...)
* For CLI, support none, effectively the same as stripping tags (i.e. we probably would just use [`wp_strip_all_tags()`](https://developer.wordpress.org/reference/functions/wp_strip_all_tags/)

Regardless of that, I think we should merge #352 as is:
* It addresses the current problem.
* It even make sense regardless of the escaping since a plugin name is not `code`.
