### ISSUE TITLE
Create Tools page

### ISSUE THREAD

**Issue by mehulkaklotar** [10up/plugin-check#32]
## Description

The plugin should introduce a new page under Tools to allow users to run checks of plugins.

## Acceptance Criteria

- Class `Admin_Page` should exist at `includes/Admin`
- `Admin_Page` class should have the `__construct()` method.
- `add_hooks()` method should exists and have the `add_action( 'admin_menu', array( $this, 'add_page' ) );` hook registering. (**NOTE:** `add_hooks()` method will be called from wherever the class is instantiated).
- The `add_page()` will have `add_management_page()` with below params.
   - `$page_title` should be "Plugin Check"
   - `$menu_title` should be "Plugin Check"
   - `$capability` should be "activate_plugins"
   - `$menu_slug` should be "plugin-check"
   - Define callback method in class `Admin_Page` for `render_page `
   - `$position` should be anything or default
 - The plugin check admin page should be available as below:
 <img width="289" alt="Screenshot 2022-11-21 at 7 56 24 PM" src="https://user-images.githubusercontent.com/4090336/203079465-f3b9eb9b-98ac-4c2c-a05b-a109ac37ab4a.png">
   
- `Admin_Page` class will have the `render_page()`, and it should print the dropdown with the list of plugins and the `check it!` button.
- Use the `get_plugins()` method to get a list of all the activated plugins, exclude `plugin check` from it and show it in the dropdown, like below:

<img width="401" alt="Screenshot 2022-11-21 at 7 58 21 PM" src="https://user-images.githubusercontent.com/4090336/203079901-f98a997e-f80e-413a-b8e3-4fc32acab9ab.png">

## Tests Coverage

**Automated Tests:**
- Create an `Admin_Page_Test` class that checks whether the `admin_menu` filter is registering properly. 
- Checks that the `Plugin Check` page is registered or not in the `global $submenu`
- Checks the output of the `render_page()` by comparing the output of the plugin's dropdown list.

**Manual Tests:**
- Login to the admin area, and find the `Plugin Check` page available under the `Tools` menu.
- Check whether the dropdown with `the list of plugins` and `check it!` button is available.
- Check on the check it button and check if that is clickable or doing any process.

**Comment by vishalkakadiya** [comment]
@jjgrainger AC for this epic is looking good to me. WDYT?

**Comment by jjgrainger** [comment]
Thanks @vishalkakadiya 

Looking good but I think we need a little more detail.

- What methods will the `Admin` class have? I think there would be a couple we need to name and define here:
    - `add_hooks()` - this method will run any actions/filters needed to register the tools page (`add_action( 'admin_menu' )`)
    - The hooks will need callbacks defined as methods on the class.
    - The `add_management_page` function also has a callback that should be a method on this class.
-  Let's expand on the test coverage:
    - What unit tests will we create? Will we be able to test some of the methods on the admin class?
    - What manual tests will we need to run?

Looking over the issues, it would be more efficient to combine this issue with #33? The initial settings page markup is only a dropdown and button. This would be simple enough to create as part of this issue and give us  more to test/review.

Can you update this issue to include a description and AC's from #33. Once the AC's for this issue is approved we can close #33.

Let me know if you have any questions. Thanks!

**Comment by vishalkakadiya** [comment]
@jjgrainger Updated this as per your comment here. Thank you! 🙂

**Comment by felixarntz** [comment]
@vishalkakadiya Some additional feedback on the ACs:
* Can we call the class something that is more specific than `Admin`? There may be more things this plugin does in the admin, and I think a more dedicated name makes sense, e.g. `Admin_Page`, to not make this class a dump for anything that happens in WP Admin.
* Let's use `add_hooks()` instead of `initialize_hooks()`, for parity with similar methods in other classes (e.g. in `Plugin_Main`). We should try to be consistent with method names.
* The `plugin_check_menu()` method name is missing a verb, which any method or function should typically have. How about calling it `add_page()`?
* Similarly, I'd suggest renaming `plugin_check_admin_page()` to `render_page()`.
* For the capability, I'd recommend using `activate_plugins` instead of `manage_options`. `activate_plugins` is closer to what our screen relates to, and it can be different who has this capability, particularly on multisite. I'd argue only users that can control plugins should be able to check plugins, at least for now.

Other than those details, it looks good.

**Comment by vishalkakadiya** [comment]
@felixarntz I have updated the description as per your comment, you can review it now. Thank you!

**Comment by jjgrainger** [comment]
Thanks @vishalkakadiya the AC's look good. I've assigned to @felixarntz for final review.

**Comment by felixarntz** [comment]
@vishalkakadiya ACs look solid now, my only remaining feedback is:

> `Admin_Page` class should have the `__construct()` which will call `add_hooks()` function.

The constructor should not call that method, instead the method should be called from wherever the class is instantiated (I assume from the plugin main class). Adding hooks from calling a constructor is not a good practice since it is an unexpected side effect from instantiation; it can also make testing unnecessarily complicated.

**Comment by vishalkakadiya** [comment]
@felixarntz makes sense, I have updated it now. Thank you! 🙌

**Comment by felixarntz** [comment]
Thanks @vishalkakadiya, LGTM!

**Comment by vishalkakadiya** [comment]
Thank you! @felixarntz @jjgrainger 🙌

**Comment by vishalkakadiya** [comment]
@jjgrainger I have raised PR for it, and it is ready for review now. Thanks!
> https://github.com/10up/plugin-check/pull/77
