### ISSUE TITLE
Show check results on the page

### ISSUE THREAD

**Issue by mehulkaklotar** [10up/plugin-check#35]
Results/errors returned from each check should be shown in the tables in the Admin area on the `Dashboard >> Tools >> Plugin Check` page.

This issue is dependent on the following:
- #34 
- #86 
- #90 
- #84 

## Acceptance Criteria

**NOTE:** Read description of #34 before checking below steps.

- `render_result_row()` should available in the `Admin_Page` class (this class is introduced in https://github.com/10up/plugin-check/issues/32)
- Add `constructor()` method in the `Admin_AJAX` class which will take the`$render_callback` variable as a constructor parameter. (`Admin_AJAX` class is introduced in https://github.com/10up/plugin-check/issues/34)
- `Admin_Page` class may/should have the `open_result_table()` and `close_result_table()` methods to format the result into the table format.
- `template-table-open.php` file template should exist at `includes/Admin/Templates` and should have the table opening tags.
- `template-table-close.php` file template should exist at `includes/Admin/Templates` and should have the table closing tags.
- `template-result-row.php` file template should exist at `includes/Admin/Templates` - this file will handle the formatting of the error/warning message into the table's row (`<tr>`) format using the `script[type="text/template"]` tags. The row format's columns can be as below:
   - Error/warning message
   - Error Type (error/warning)
   - Error/Warning Standard name (e.g., WordPress.XSS.EscapeOutput.OutputNotEscaped, and so on. )
   - File name and path - on which error/warning occurs
   - Line and Column numbers - on which error/warning occurs
- `open_result_table()` method should includes the `template-table-open.php` template in it.
- `render_result_row()` method should includes the `template-result-row.php` template in it.
- `close_result_table()` method should includes the `template-table-close.php` template in it.
- `Admin_Page` class will use the `initialize_page()` method(see https://github.com/10up/plugin-check/issues/32). This method should call all three template functions to create the template markup in the admin footer with the `admin_footer` action.
    1. `open_result_table()`
    2. `render_result_row()`
    3. `close_result_table()`

**NOTE:** On the fresh admin screen, the table not exist on the page, and once results are returned, the table will be created and rendered, but that will be handled in #84.

## Tests Coverage

**Automated Tests:**
- Write a test case for the `Admin_Page::render_result_row()`.
- Write a test case for the `Admin_Page::open_result_table()` and `Admin_Page::close_result_table()`.
- Write a test case to test the row template markup.

**Manual Tests:**
- Once the user clicks the `Check it!` button, check if the proper HTML table and table row are showing up and appending on the screen.

**Comment by vishalkakadiya** [comment]
@jjgrainger I have updated this epic now, please review it before sending it to Felix. Thank you!

**Comment by jjgrainger** [comment]
Thanks @vishalkakadiya 

I think this needs more detail and adjusted based on my comments here https://github.com/10up/plugin-check/issues/34#issuecomment-1403393327

- The AJAX handler will return the results for each check within the response. This data needs to be formatted and injected onto the page with JavaScript.
- There will also be a template used for each row of the results returned. It would be good to detail how these template parts will be created and used by the JS.
- What information will be displayed on each row? Off the top of my head there will be:
    - Error/warning message
    - type (error/warning)
    - File name and path
    - Line and column numbers

Let me know if you have any questions. Thanks!

**Comment by vishalkakadiya** [comment]
@jjgrainger Updated the description as you suggested. Thank you!
 
CC @felixarntz

**Comment by felixarntz** [comment]
@vishalkakadiya Leaving some feedback here: Most of the ACs look good, but I think we should limit this to just introducing the formatting method, not actually call it anywhere yet, to unblock this and not have it depend on all the other issues that are still pending.

Please review my feedback on #34 first. Some of my feedback below will make more sense afterwards.

* Instead of adding a `format_output()` method in `Admin_Checks` / `Admin_AJAX`, we should rather add this as a public method in `Admin_Page`, since that is technically the class responsible for controlling output. We could call it `Admin_Page::render_result_row()`.
* You can add a constructor parameter like `$render_callback` to `Admin_AJAX`, which the `Admin_Page` class can pass that new method to when instantiating the class.
* You mention using a table, but then we also need to have a way for the table itself to be rendered. Maybe we should also have methods `Admin_Page::open_result_table()` and `Admin_Page::close_result_table()`?
* Alternatively to even using `Admin_AJAX` for the output, I think it would be an even cleaner solution to keep the output fully controlled by `Admin_Page` and its script. We could make the templates available to the script by using `script[type="text/template"]` tags. These support variables and can be used by the `wp.template()` function in JavaScript. This way, we can keep the `Admin_AJAX` code focused on only returning raw data JSON results.

**Comment by vishalkakadiya** [comment]
@felixarntz I have updated the ACs as per your feedback, please review it. Thanks!

**Comment by felixarntz** [comment]
@vishalkakadiya Now that we broke apart #34 into #34 and #84, the following 2 points should be handled as part of #84 instead:
> Once the `run_checks()` method is called via an ajax call, this method calls the check runner classes and formats the output in the format in the JSON format.

> The `plugin-check-admin.js` JS file (introduced in #34) will replace the template variables using `wp.template()` and append the new row in the table to show the new error/warning related to the plugin.

That is because the full routes and JS script will only be implemented as part of #84, and #34 and #35 need to be implemented before #84.

Other than that the ACs look good. Just one thing, it would be good to mention that the `Admin_Page` class should output the `script[text/template]`s so that they can later be used in the JS script. Note that we need 3 of those templates to be output: One for opening the result table, one for closing the result table, and one for rendering a single row. (Even though only the latter uses any variables, all 3 of them will need to be called in JS.)

**Comment by vishalkakadiya** [comment]
@felixarntz I have updated the AC as per your feedback now. Thanks!

**Comment by felixarntz** [comment]
@vishalkakadiya Almost good to go, but I'd argue a cleaner approach for the templates would be to not output them together with the page, but rather in the footer (e.g. in the `initialize_page()` method add an action to `admin_footer` to print the templates).

**Comment by jjgrainger** [comment]
Thanks @felixarntz I've updated the AC's to use the `initialize_page()` and `admin_footer` to render the table template. Ready for you to review.

**Comment by felixarntz** [comment]
@jjgrainger ACs LGTM!
