### ISSUE TITLE
Create Plugin_Main class

### ISSUE THREAD

**Issue by mehulkaklotar** [10up/plugin-check#4]
## Description

The Plugin Main class will be used as the plugin’s most central class and will be used to bootstrap the Plugin Check plugin. Using a class allows all bootstrapping logic for the Plugin Check plugin to be consolidated in a single class, separating it from check logic and making it easier to maintain. This class will be responsible for setting up the plugin checker by registering hooks in WordPress and any other logic required, for example:

- Adding hooks and filters to register the plugin check WP-CLI command
- Enqueuing any assets required for the Plugin Check admin screen
- Localization support

`Plugin_Main` class will be instantiated in the `plugin-check.php` file of the Plugin Check plugin. It will accept a single `$main_file` parameter in its constructor which is used to create the plugin context. The context of the plugin will be handled by the protected property `$context` (`Plugin_Context`).

## Acceptance Criteria

- A new `Plugin_Main` class is created
- The class contains a single protected property named `$context`
- The class `__construct()` method accepts a single parameter
    - `(string) $main_file` - A string representing the absolute path to the plugin main file
    - The `$main_file` parameter is passed to a new instances of the `Plugin_Context` class
    - The new `Plugin_Context` instances is assigned to the protected `$context` property
- An empty `add_hooks` method exists in the `Plugin_Main` class to be updated later to register hooks to WordPress
- A new `Plugin_Context` class is created. This class will be empty and setup as a basic scaffold for #5 
- The `plugin-check.php` file is updated to include the following:
    - Constant `WP_PLUGIN_CHECK_VERSION ` defined with the plugin version
    - Constant `WP_PLUGIN_CHECK_MINIMUM_PHP ` defined with the minimum PHP version required for the plugin check plugin to work
    - A `wp_plugin_check_load` function exists which:
        - Checks the current PHP version is greater than the `WP_PLUGIN_CHECK_MINIMUM_PHP` constant
        - Checks the `vendor/autoload.php` file exists in the plugin
        - If the above checks pass
           - The `vendor/autoload.php` file is required in
           - The `Plugin_Main` class is instantiated passing `__FILE__` into the constructor
           - The `add_hooks()` method is called on the instantiated `Plugin_Main` object

**Comment by felixarntz** [comment]
@jjgrainger The ACs here look good, but I think a problem here is that they already refer to `Plugin_Context` which is implemented as part of #5. So we should:
* either implement both in the same issue
* or use this issue just to scaffold an almost empty `Plugin_Context` class just so that the code here technically works
* or implement #5 before #4

Either approach works, I don't have a strong preference; but for things like this it is crucial to define the sequence as part of ACs so that the scope of the issue is clear.

My only other more minor question here is on the instantiation of `Plugin_Main`: Is the idea that the `plugin-check.php` file would simply have `new Plugin_Main( __FILE__ )` or it happen in a certain hook or so?

**Comment by jjgrainger** [comment]
Thanks @felixarntz 

I've updated the ACs to include the points you've raised.

For the `Plugin_Context` class, I believe the second option is best where we create an empty `Plugin_Context` class so the code does not break and the code for the class is implemented in #5

**Comment by felixarntz** [comment]
@jjgrainger Thanks, LGTM!
