### ISSUE TITLE
Requires related plugin header check in readme

### ISSUE THREAD

**Issue by ernilambar** [10up/plugin-check#405]
Related: https://github.com/WordPress/plugin-check/issues/198

For following two headers, we accept fields either in readme file or main plugin file.

- `Requires at least`
- `Requires PHP`

We could raise **ERROR** or **WARNING** if those fields are missing from both files.

It seems preference is given to plugin file header. May be we could create separate Check instead of keeping inside `plugin_readme` check.

**Comment by ernilambar** [comment]
@foosantos Please provide confirmation on this one also.

**Comment by swissspidy** [comment]
Some context: 

Since WordPress 5.8, plugin [readme files are not parsed for requirements](https://core.trac.wordpress.org/ticket/48520). This means that, in core, `Requires PHP` and `Requires at least` are always parsed from plugin’s main PHP file. The place for the `Tested up to` header remains in `readme.txt` for the time being, as it's not used by WordPress core.

IMHO these headers are not mandatory and should never trigger an error. Not sure they should even trigger a warning, after all they are optional.

What could be useful to check is that `Requires PHP` and `Requires at least` (if present) follow the right format. These should be numbers only, so `7.0` and not `PHP 7.0`. Or `6.5` and not `WP 6.5`.

**Comment by ernilambar** [comment]
In the readme validator, message is shown in Notes like:
```
The Requires at least field is missing. It should be defined here, or in your main plugin file.
The Requires PHP field is missing. It should be defined here, or in your main plugin file.
```

There is **should** in the message. So I assumed it is required. May be it is required in the directory?

![Screenshot 2024-01-30 at 2 28 38 PM](https://github.com/WordPress/plugin-check/assets/2098823/ef15307f-6a93-4be0-89a9-01e27a3c1026)

**Comment by swissspidy** [comment]
> There is should in the message. So I assumed it is required. May be it is required in the directory?

I think this is just outdated. Again, all the data is parsed from the main plugin file.

**Comment by ernilambar** [comment]
Closing this for now. We can reopen in the future if needed.
