### ISSUE TITLE
Create test DB tables using object-cache.php to generate demo data

### ISSUE THREAD

**Issue by mehulkaklotar** [10up/plugin-check#42]
## Description

A clean environment is required for checks to run smoothly. There are a few possible scenarios that can be followed to run checks cleanly without affecting the site. So that users can run it on any site environment like production or staging. 

The approach should be not to generate test content to the primary database tables, and all modifications to the site DB should be made through test DB tables. The plugin should create test DB tables with a different prefix specially generated through the plugin to populate test data for the site. Using [wpdb::set_prefix](https://developer.wordpress.org/reference/classes/wpdb/set_prefix/), the plugin can change the base prefix of the site test DB tables. This approach can be run on the production site as well because the plugin is generating tables for demo content on need in the test tables. 

Also, this approach will only be used for runtime checks that require DB operations to run. Runtime checks should only be run if the plugin is already active on the site. The plugin can prompt the user to activate the plugin when the check is initiated.

The plugin can use its own **object-cache.php** drop-in file added into the wp-content directory which overrides the DB table prefix. It can be used to run early and pause plugins other than the one being tested. It should not actually implement an object cache. If the site is already using its own object-cache.php file, the file should be renamed and conditionally required by the plugin checker’s object-cache.php file (see below note on an additional consideration there).

This approach will need to add to the database directly and preparations will need to do clean-ups to the database content. For example, some checks would require demo content to be added to the test DB tables via preparations.

**Note**: If a site is using a persistent object cache, it should be paused for the check requests as well so that it doesn’t add any of the demo test data into the real object cache of the site. The plugin can bypass it using the object-cache.php file.

## Acceptance Criteria

- A `Runtime_Environment_Setup` class exists in `includes/Checker`
    - The `Runtime_Environment_Setup` class will be responsible for setting up the WordPress environment to run Runtime checks.
    - A public `setup()` method exists in the class and will handle the following steps:
        - Creates the demo database tables (if they do not already exist)
            - The demo tables will use a new `wppc_` prefix.
            - The demo tables will be populated with the required installation data by running the regular WP installation functions.
        - Add the object-cache.php drop-in file to the wp-content folder. If an object-cache.php file already exists, this step is skipped.
    - A public `cleanup()` method exists in the class to reverse the changes from the `setup()` method
        - Delete the demo database tables.
        - Remove the plugin checker object-cache.php file. 
- A `Plugin_Request_Utility` class exists in `includes\Utilities`
    - A public static `initialize_runner()` method  exists in the class that will handle the following steps.
        - Instantiate both runner classes
            - #14 
            - #15 
        - Call both runner classes `is_plugin_check()` methods.
        - If the `is_plugin_method` call returns true, the runners `prepare()` method is called.
        - If any check requested is a `Runtime_Check`, the `prepare()` method will update the wpdb prefix with [wpdb::set_prefix](https://developer.wordpress.org/reference/classes/wpdb/set_prefix/) to match the demo tables prefix.
    - A public static `get_runner()` method exists.
        - This method returns the runner instance that is being used for the current request, or `null` if neither is being relevant (e.g. when it is not a plugin checker request).
- Include an `object-cache.php` drop-in file.
    - The object-cache.php drop-in file will call the `Plugin_Request_Utility::initialize_runner()` method. 

### References
Below are issues/PR's from the Performance Lab plugin related to the object-cache.php drop in.

- https://github.com/WordPress/performance/issues/612
- https://github.com/WordPress/performance/pull/616
- https://github.com/WordPress/performance/issues/551
- https://github.com/WordPress/performance/pull/553

**Comment by felixarntz** [comment]
@jjgrainger Some feedback on the ACs:
> If an object-cache.php drop-in file already exists, it should be renamed and conditionally required into the plugins object-cache.php file

This is risky, as seen in all the feedback for the similar approach taken in the Performance Lab plugin. FWIW I'm still thinking about a cleaner way to solve it there.

For the plugin checker specifically, I think we need to revise this: One thing that's different here form the PL plugin is that we only need this `object-cache.php` file to be present while a check is running. So potentially there are ways to conditionally place the file only for that and then delete it again which would reduce the chance for conflicts. But thinking this through, I believe that would only work for the AJAX based approach where we run tests through several separate WordPress requests - in CLI it's all one request, so by the time we place the drop-in that code has already run so it would be too late.

Maybe the best for now is to only place the `object-cache.php` drop-in if there is no other one present. If we go with that for now, let's open another issue to explore how we can enhance it in the future in a way that also works when there is already an _actual_ `object-cache.php` file present.

> Include an `object-cache.php` drop-in file to create test database tables for demo content required for runtime checks.

How would we create the DB tables? This is a bit vague; we should probably only create the tables before the first check runs and delete them after the last check has run; not add and delete them in every single AJAX request. It's fine for the tables to stick around for a couple seconds or minutes, the only thing that is critical is that the WPDB prefix only points to them in the plugin checker related requests, not regular WP requests.

> * After checks have run, the following clean ups steps will occur if a single runtime check was processed.
>     * Reset the WPDB prefix to it's original prefix
>     * Remove the demo database tables
>     * Restore the original object-cache.php drop-in file

The 1st sub bullet point makes sense, but see my previous feedback on the 2nd and 3rd sub bullet points.
Regarding point 2:
* We probably shouldn't remove the database tables in every single check, as that would be wasteful; we should rather only remove them after an entire plugin checker run.
Regarding point 3:
* Not sure whether conditionally replacing and restoring an `object-cache.php` file would work when in a WP-CLI context. The CLI command (like anything from the Plugin Check plugin) will only be available after plugins have loaded, which is already too late for us to place the `object-cache.php` and have it loaded in the same request. Placing it or restoring the original would only affect subsequent requests.

Last but not least: It would be great to include a few references to the relevant PL plugin issues / PRs here. There are certain things we should do similarly to there, so it is crucial for issues to point to those code examples, rather than the PR author having to think about the same approach themselves again. At the same time, there are also things which have proven to be problematic in how the PL plugin does it, so it would be useful to refer to those as well.

**Comment by jjgrainger** [comment]
Thanks @felixarntz 

> Maybe the best for now is to only place the object-cache.php drop-in if there is no other one present. If we go with that for now, let's open another issue to explore how we can enhance it in the future in a way that also works when there is already an actual object-cache.php file present.

I'm happy with this approach and will create a new issue for the follow up work here.

> How would we create the DB tables? This is a bit vague; we should probably only create the tables before the first check runs and delete them after the last check has run;

This was the intention here but might not have been clear in the AC's. I'm wondering if the database table creation (and maybe setting the prefix) should be it's own Preparation that we can make part of the `Universal_Runtime_Preparations`. This would mean the database tables are created once before running checks and removed once all checks are complete. However, this may not be the case when running checks via AJAX.

> One thing that's different here form the PL plugin is that we only need this object-cache.php file to be present while a check is running.

Thinking this over I'm wondering if we need a kind of pre-run setup step where we add our own object-cache.php drop-in and create the demo database tables. This would be separate from the requests that run checks and would be done before that request is made.

So for AJAX requests, when the user hit's the 'Check Plugin' button, we can check to see if our object-cache.php file and the database tables exists. If not, we first create those in that first AJAX request. Then the subsequent AJAX requests will run the individual checks. Once all checks have been run a cleanup request is sent to remove the object-cache.php and database tables.

For CLI, as it's handled in one request, we could introduce a `wp plugin check-pre-run` command. This command will handle creating the object-cache.php and database tables. Then the developer can run the `wp plugin check` command to run checks in a new request. Once complete, the developer would have to run a cleanup command to remove the object-cache.php and database tables. The additional commands add extra steps but we can prompt the pre-run command if the check command is run first and notify the user the clean up command should be run at the end of the check command.

Interested to hear your thoughts and happy to talk through it on a call if thats easier.

Thanks

**Comment by felixarntz** [comment]
@jjgrainger What you're saying sounds right to me; we wouldn't be able to handle the DB tables in a universal preparation since it would still run on every check request. For AJAX, indeed it would mean that it would run in every single check request again, so that's not a good option. For CLI it would work, but even then there's still the challenge of the `object-cache.php` drop-in and that it would not be placed in time.

I think the concept of some sort of pre-run and post-run logic that just runs once before and after the entire set of checks and is explicitly triggered (e.g. by extra AJAX requests at the start and end of the process, or some pre and post commands on CLI) sounds right.

For AJAX, we can easily handle that. For CLI, some "pre run" and "post run" commands like you're saying might work, but that would be a cumbersome experience. I wonder whether WP-CLI maybe has some sort of hook system maybe that allows to run certain pre or post logic in separate requests from the actual command execution, that would be neat. Regardless of that detail, I think we should work towards a separate piece of logic for this one-time preparation and one-time cleanup.

Not sure what we should call it though? Naming is hard. We already have `Universal_Runtime_Preparation`. In a way, what we're talking about here is also a "universal runtime preparation", since creating the DB tables and placing the `object-cache.php` file as well only really matters when doing runtime checks. If only static checks should be run on a plugin, these steps would be unnecessary entirely (something to keep in mind generally: runtime checks are only allowed to run if the plugin to check is already active). Since our new concept here is also different from all other preparations in that the preparation should _not_ immediately be cleaned up again in the same request, I'd suggest we do not use the "preparation" name here at all and don't rely on that same interface either. Maybe just a completely standalone class like `Runtime_Environment_Setup`?

**Comment by jjgrainger** [comment]
Thanks @felixarntz 

I agree with your points here and a `Runtime_Environment_Setup` class sounds good to hold the logic for the pre/post run steps.

As you stated for AJAX we can handle this easily with additional requests at the start/end of the process.

For CLI, [there are hooks](https://make.wordpress.org/cli/handbook/references/internal-api/wp-cli-add-hook/#notes) we could use that will run before WordPress is loaded that looks promising (`before_wp_load` or `before_wp_config_load`). One of these hooks can be used to setup the runtime environment and the cleanup steps can then be registered to the shutdown hook.

I'll update the AC's here to reflect this.

Thanks

**Comment by jjgrainger** [comment]
@felixarntz I've updated the AC's based on the feedback, please can you review. Thanks.

**Comment by felixarntz** [comment]
@jjgrainger The ACs look good regarding the `Runtime_Environment_Setup`, just one thing there:
> Data will be added to the demo options table for WordPress to run correctly. This would include options for active plugins and themes, site URL and others.

Maybe worth clarifying that this should not be done manually. We simply need to call the regular WordPress install function to populate that data as needed.

For the `object-cache.php` file, the ACs are now a bit outdated and partially incorrect:
> drop-in file to create test database tables for demo content required for runtime checks

The drop-in file should not create the test database tables as that will now happen through a dedicated request (in AJAX) or pre hook (in WP-CLI).

> instantiate the following runner classes and call their `setup_checks()` method if required

This method no longer exists, or at least is not public. I think it's sufficient to describe that the `prepare()` method of the runner should be called _if_ the request is for a runtime check. Also, maybe clarify `if_required`? What are those requirements?

> If there is at least 1 runtime check to process, the drop-in file will create the additional database tables required and update the wpdb prefix

See above, it should not create the tables. It should only change the prefix. Though, FWIW, I actually wonder why don't we just move that to the runner classes? It also should only happen when at least one runtime check is being run, and I don't see why this code should live directly in the `object-cache.php` drop-in.

A general note: We should keep the code in that drop-in as light as possible as it's a file that's being copied around and has chances for conflict etc; also it's hard to make updates to it since it then lives outside of the plugin's own directory. So it's best to keep that file as minimal as possible and have any logic within classes in the plugin that this file simply calls. Because of that, I wonder whether we should rather use a class like `Plugin_Request_Utility` (which I also mentioned for another purpose in https://github.com/10up/plugin-check/pull/73#discussion_r1103188992), with a method `initialize_runner()`, to encapsulate all the logic described in the `object-cache.php` drop-in section. The `object-cache.php` file itself could then just be:
```php
// Plugin file header...

Plugin_Request_Utility::initialize_runner();
```

Having a class like this will also be useful later when we need to call the runner's `run()` method, as we should be able to access the same class instance then that was already instantiated here. So for that we could later add a method like `get_runner()` to access that same instance (that can happen in a separate issue though once we get to implementing the CLI and AJAX logic).

Let me know what you think.

**Comment by felixarntz** [comment]
@jjgrainger Another note unrelated to the ACs: Regarding the WP-CLI hooks like `before_wp_load`: Just like that, those won't work for the same reason that we need the `object-cache.php` file: The CLI command comes from the plugin, so it won't be loaded in WP-CLI before WP is loaded.

However I have asked the maintainer of WP-CLI about this already, and he mentioned there is a way to pull in a command directly within a CLI call like `wp --require=custom-command.php`. We can probably use that eventually so that you would have to pull in the command file directly when calling the command, e.g. something like `wp --require=./wp-content/plugins/plugin-check/includes/CLI/Plugin_Check_Command.php plugin check ...`. There are specific requirements that the command file has to fulfill for that to work, but we can work out those details later.

**Comment by jjgrainger** [comment]
Thanks @felixarntz I've updated the AC's based on your feedback.

**Comment by felixarntz** [comment]
@jjgrainger ACs LGTM!

Made just a tiny change just to clarify that `get_runner()` also needs to potentially return `null`.
