### ISSUE TITLE
MariaDB generating error when we are using %s as placeholder for table name when CS(code sniffer) suggest to used %s instead %i 

### ISSUE THREAD

**Issue by crathod-io** [10up/plugin-check#439]
**ERROR WordPress.DB.PreparedSQLPlaceholders.UnsupportedIdentifierPlaceholder**

The %i modifier is only supported in WP 6.2 or higher. Found: "%i".

**Comment by crathod-io** [comment]
![Screenshot from 2024-03-20 18-29-09](https://github.com/WordPress/plugin-check/assets/155540960/c3a3ea0a-88fa-4744-8e47-14a325ad9329)

**Comment by swissspidy** [comment]
Here we go again :-)

Which plugin is this for?

If this happens in your own plugin, the error message is pretty self-explanatory. The "%i" modifier is only supported on WP 6.2+, so if you support older versions you need to fall back to something else.

**Comment by swissspidy** [comment]
Also, it would really help if you could provide more context instead of just copy-pasting the error message. What is it you want to achieve, i.e. is this a bug in your own plugin that you want to address, or do you believe there is an issue in Plugin Check that needs to be resolved? Without more information this ticket is not really actionable.

**Comment by swissspidy** [comment]
Closing this as not applicable because this check is working as expected.

The error tells you a potential issue with your code that you should address.

If your plugin is supposed to work for WordPress versions older than 6.2, you cannot use the "%i" placeholder in queries, as older versions don't support it.
