### ISSUE TITLE
Composer warning when running unit test

### ISSUE THREAD

**Issue by ernilambar** [10up/plugin-check#484]
When I run test using command `npm run test-php`, following warning message appears after `Starting 'composer install --no-dev' on the tests-cli container. `

```
Composer could not detect the root package (wordpress/plugin-check) version, defaulting to '1.0.0'. See https://getcomposer.org/root-version
```

**Comment by swissspidy** [comment]
Probably just a side effect of running Composer within wp-env? It doesn't happen when you run any Composer commands locally. In wp-env it might not have proper access to the `.git` folder or something, hence the warning. Also note that adding a version to `composer.json` is considered a bad practice, so I would not do that.

All in all, since this is just a warning occuring in wp-env, personally I would not bother looking into it.

**Comment by ernilambar** [comment]
@swissspidy There is also another warning. Not sure whether it is Docker issue or wp-env issue.

```
WARN[0000] /Users/johndoe/.wp-env/27c26e959817828ceadc3831fb10f454/docker-compose.yml: `version` is obsolete 
```

**Comment by swissspidy** [comment]
That's simply wp-env that needs to be updated after docker-compose deprecated that field. That line needs to be removed: https://github.com/WordPress/gutenberg/blob/12518a05af35aa504f7c8b086cb6f255cf094f25/packages/env/lib/build-docker-compose-config.js#L178

**Comment by ernilambar** [comment]
Since both issues needs to be fixed upstream, I am closing this issue.
