### ISSUE TITLE
Getting nonce verification needed for every instance of a $_GET or $_REQUEST var

### ISSUE THREAD

**Issue by davidperezgar** [10up/plugin-check#549]
> I am getting a “nonce verification needed” warning for every instance of a $_GET or $_REQUEST variable in a conditional when there is no form submission, ajax query or other type of transmission happening. These are not hard to ignore, though a bit annoying. This is also troublesome because I am editing a plugin that was flagged as not secure by the repository review team and I need to clear all errors and warnings using this plugin. If I am wrong on thinking that nonces are not required just because a $_GET or $_REQUEST is used in the code, please let me know. I could be wrong on that point.

https://wordpress.org/support/topic/getting-nonce-verification-needed-for-every-instance-of-a-_get-or-_request-var/#post-17911660

**Comment by swissspidy** [comment]
That's how the PHPCS sniff works 🤷 

See https://github.com/WordPress/WordPress-Coding-Standards/wiki/Fixing-errors-for-input-data#nonces and https://github.com/WordPress/WordPress-Coding-Standards/wiki/Sanitizing-array-input-data

If they think there are false positives, they can be reported to WPCS.

**Comment by davidperezgar** [comment]
Let's check and report if they are false positives.

**Comment by dd32** [comment]
These are almost always false positives in my experience, except when they're not.

Nonces can't/shouldn't always be used either; a front-end form on a website should not have a nonce unless the user is logged in.

**Comment by davidperezgar** [comment]
Yeah, that's why we make severity to 6, so it shows warning for wporg submissions.

**Comment by DavidAnderson684** [comment]
I don't think this check is the proper way to solve the real problem.

The real problem is that WordPress core has no API for retrieving variables from query strings or POST bodies. So, every plugin accesses `$_GET` or `$_POST` directly, and then has to remember to unslash (for compatibility with 2008 or something) and gets flagged by Plugin Checker for perhaps (or perhaps not) needing a nonce check.

If there were a proper API then you could just call the API and thousands of plugin author and plugin team man-hours (and the security holes themselves) could be spared.

`$var = wp_retrieve_get_var('variable_name', NON_AUTHENTICATED); // or whatever`

There are whole classes of things like this. For example, the assumption that values retrieved from `__()` potentially contain attacker-contributed HTML injections.... that's a bit crazy; why not just modify the wordpress.org translation tools so that translation files can't include HTML? Or modify the definition of `__()` so that it can't include HTML? Again, that'll save hundreds or thousands of man-hours in the long run. (There might be some legacy breakage there, of course, but only of things that were already broken: HTML tags just don't belong in translations; plugin authors could be given 12 months to get up to speed, `__doing_it_wrong()` can be invoked to help them, etc.).

**Comment by davidperezgar** [comment]
Yes, I'm agree that core could give some API functions to work with POST and GET, but that's not where you can ask. It's on a ticket or issue in WordPress core.

**Comment by ernilambar** [comment]
If possible, this should be fixed upstream in WPCS.
