### ISSUE TITLE
Error: Your plugin has no license declared in Plugin Header

### ISSUE THREAD

**Issue by jcvignoli** [10up/plugin-check#550]
Hello,
The workflow fails to run with the following message:
`Error: Your plugin has no license declared in Plugin Header. Please update your plugin header with a GPLv2 (or later) compatible license.`

My readme licence tags:
```
License: GPLv3
License URI: https://www.gnu.org/licenses/gpl-3.0.en.html
```
Thanks in advance for checking it!

**Comment by swissspidy** [comment]
What's your plugin? Does this also happen when you install the [Plugin Check](https://wordpress.org/plugins/plugin-check/) plugin on your development site?

**Comment by jcvignoli** [comment]
This is my plugin: https://wordpress.org/plugins/lumiere-movies/
Yes, I get the same error on a local dev site.

Edit: I just noticed on local env that it complains about the initial file (lumiere-movies.php), not readme.txt. I therefore paste the code in that file:
```
 * @package   lumiere-movies
 * @author    jcvignoli
 * @license   GPL-3.0 <https://www.gnu.org/licenses/gpl-3.0.en.html>
 * @link       https://wordpress.org/plugins/lumiere-movies/
 * @since      3.0
```

**Comment by swissspidy** [comment]
In that case, this would be an issue with the Plugin Check plugin, not with this GitHub Action. Issues with the plugins hould be reported at https://github.com/WordPress/plugin-check/.

That said, Plugin Check does not look at PHPdoc block like yours. It needs to be a **proper plugin header**. Example:

https://github.com/WordPress/performance/blob/b319595c3c1ca567bcca122dca561bc714d772e4/plugins/performance-lab/load.php#L11-L13

See https://developer.wordpress.org/plugins/plugin-basics/header-requirements/ for more detailed information about plugin headers.

**Comment by adlwebsolutions** [comment]
Error: No license defined. Your plugin has no license declared. Please update your readme.txt with a GPLv2 (or later) compatible license.
I check the readme.txt validator, but the tool also giving an error , but I corrected everything, still it is showing the same issues( The Tested up to field is missing.
The Stable tag field is missing or invalid. Note: We ask you no longer attempt to use /trunk/ as stable, so that all plugins can be rolled back.
The License field is missing. [A GPLv2 or later compatible license](https://www.gnu.org/licenses/license-list.en.html) should be specified.
The Short Description section is too long and was truncated. A maximum of 150 characters is supported. )

**Comment by ernilambar** [comment]
@adlwebsolutions Can you please provide the readme file you are testing?

**Comment by adlwebsolutions** [comment]
now i uploaded the plugin, and thanks for asking,

**Comment by davidperezgar** [comment]
Ok, let us if you have any problem in a new issue.
