### ISSUE TITLE
Create abstract class PHP_CodeSniffer_Check

### ISSUE THREAD

**Issue by mehulkaklotar** [10up/plugin-check#8]
This abstract class will be used to create concrete check classes that perform static analysis. This class will provide foundational methods that allow concrete classes to define code standards and sniffs to test the plugin code against. It will also contain an instance of `PHP_CodeSniffer\Runner` to run the tests and return the results to be processed.

## Acceptance Criteria

- An abstract `Abstract_PHP_CodeSniffer_Check` class exists
- The `Abstract_PHP_CodeSniffer_Check` implements the `Check` interface
- The class contains a `public function run( Check_Result $result )` method
- The `run()` method accepts a single `$result` parameter
- The `$result` parameter is an instance of the `Check_Result` class
- The `run()` method handles the logic to
    - Require in the PHPCS autoloader from composer vendor folder
    - Backup the original `$_SERVER['argv']` array to a `$original_cmd_args` variable
    - Generate the arguments to pass to PHPCS by passing `$result->plugin()` to `Abstract_PHP_CodeSniffer_Check::get_args()` method
    - Set the `$_SERVER['argv']` array to the arguments to pass to PHPCS
    - Run PHPCS using an instance of `\PHP_CodeSniffer\Runner` class
    - Restore the original command arguments from `$original_cmd_args` variable
    - Add the results from PHPCS to the `$results` object using the `$results->add_message()` method
- The `Abstract_PHP_CodeSniffer_Check` contains a `abstract function get_args( Check_Context $context )` method
- The `get_args()` method accepts a `$context` parameter
- The `$context` parameter is an instance of `Check_Context`
- The `get_args()` method will be written in concrete Check classes to return the arguments to pass to PHPCS

**Comment by felixarntz** [comment]
@jjgrainger One nit-pick:
> - The class contains a `public function run( Check_Result $result )` method
> - The `run()` method accepts a single `$result` parameter
> - The `$result` parameter is an instance of the `Check_Result` class

The last two points here seem a bit overkill/unnecessary as the first point already clarifies that. :)

More importantly though, some feedback regarding the `get_args()` method:
* The way you outline it here will make for a rather cumbersome API when it comes to individual classes implementing `get_args()`, because all arguments are simply command line arguments, i.e. in an indexed array, and the first entry has to be an empty string - that's confusing.
* I would suggest at a minimum we implement this in a cleaner way where `get_args()` only returns an associative array of arguments (e.g. including a key `extensions` with value `php`). There could then be a private helper method that parses the associative array into the full data and format expected by `$_SERVER['argv']`.
* The plugin path shouldn't need to be provided to the method, any PHPCS check should look in that plugin and nowhere else. So providing control over that to the `get_args()` method is misleading and error-prone.
* Similarly, I'd argue even the `report` and `report-width` arguments need to have the specific value outlined; for example if `report` is not passed as `Json`, we would need to implementing parsing out the report data in different formats, where I'd wonder why we would want to do that. Forcing it as JSON and then only having to implement parsing out the report data from a JSON string makes more sense to me.
* So I think some of these arguments should be enforced and not be covered by `get_args()`, as per the above.
