### ISSUE TITLE
Handle running checks in loop and return output

### ISSUE THREAD

**Issue by vishalkakadiya** [10up/plugin-check#84]
## Description
Handle running checks one by one and return output.

This issue is dependent on the following:
- #34 
- #86 
- #90 

## Acceptance Criteria
- Update the `run_checks()` method in the `Admin_AJAX` class to handle running checks and returning a response.
    - The `run_checks` method will first verify the request using the nonce passed and If invalid will return an error response.
    - Then the `AJAX_Runner` instance is gathered by calling the `Plugin_Request_Utility::get_runner()`.
    - If the `Plugin_Request_Utility::get_runner()` returns `null` a new instance of the `AJAX_Runner` class should be created.
        - As part of creating the `AJAX_Runner` instance, the `set_check_slugs()` and `set_plugin_slug ()` methods should be called passing in the appropriate values taken from the request. 
    - Then the `AJAX_Runners` `run()` method is called and the `Check_Results` instance returned is stored in a variable.
    - If the `run()` method throws an exception, the error message is captured and returned in an error response to the client. The `admin-plugin-check.js` file will handle the error and display it on the admin page for debugging. Any further check requests will not be sent. 
    - The results are then passed to the protected `format_results()` method in the `Admin_AJAX` class. This method will handle formatting all results into an array of messages, with each message being an object with the following properties.
        - `message` - The error or warning message.
        - `type` - Either `error` or `warning`.
        - `standard` - The standard or check name.
        - `file` - The filename and path
        - `line_column` - The line and column numbers the error/warning occurred.
    - A response is returned containing the following information
        - `success` - `true` or `false` as to whether the check run was successful.
        - `results` - The array of messages returned by `format_results()`. Can be an empty array.
        - `check` - The slug of the check that was run.
        - `error` - `false` if there were no critical errors when running checks, `false` if the check run was successful.
- Update the `plugin-check-admin.js` to send requests to the `admin-ajax.php` endpoint to run checks.
    - The `checks_to_run` returned by the `plugin_check_get_checks_to_run` action will be used to send requests for each individual check.
    - The first check is removed from the array and sent in the request.
    - The AJAX request will send the following:
        - A array containing a single check slug to be run
        - The plugin name to check.
        - A valid nonce.
    - On a successful response:
        - The messages returned will be injected into the admin page using the templates setup in #35 
        - The next check in the `checks_to_run` array  is removed and used in the next request. This process will repeat until the `checks_to_run` is empty and the last check is run.
         - When  all checks have been run and the `checks_to_run` array is empty the runtime environment cleanup is executed by making a request to the `admin-ajax.php` endpoint with the `plugin_check_cleanup_environment` action (implemented in #86)
    - On a error response:
        - A user-friendly error message is displayed in the admin page with the error that occurred.
        - The runtime environment cleanup function will be run by making a request to the `admin-ajax.php` endpoint with the `plugin_check_cleanup_environment` action (implemented in #86)

**Comment by felixarntz** [comment]
@vishalkakadiya Some notes regarding the eventual ACs here:
* We need to access the `AJAX_Runner` instance via the `Plugin_Request_Utility::get_runner()` method that is being implemented in #80. (We need to include error handling, in case the instance is not set or not an `AJAX_Runner` instance.)
* The ACs should include which AJAX actions we need. I think at the minimum we will need individual AJAX actions to  get the list of checks to run, prepare the environment, run a single check (called multiple times, one by one), then clean up the environment.

**Comment by jjgrainger** [comment]
Thanks @felixarntz 

I had created a separate issue with AC's to handle to the environment setup and cleanup for AJAX here https://github.com/10up/plugin-check/issues/86

I've referenced this in the AC's here but updated this ticket to tackle the action to get a list of checks to run and to run a single check which is called multiple times.

This is ready for you to review. Thanks!

**Comment by felixarntz** [comment]
@vishalkakadiya The ACs on this issue are still quite a bit, I think we should break this down at least into 2 issues. Most importantly, I think the `plugin_check_get_checks_to_run` endpoint is a dependency for #86 (see my latest comment there), not vice-versa. It will also be a lot simpler to implement that endpoint than it will be to implement the rest of the ACs. Can you please open a new issue for just the `plugin_check_get_checks_to_run` endpoint and keep this issue here for the rest?

Two high level points regarding the ACs:
* For `plugin_check_get_checks_to_run`, we also need to consider that runtime checks must only be run if the plugin to check is active. So it is critical that the plugin basename is also passed to this endpoint, and checks are returned depending on that. Also consider the following:
    * If `$_REQUEST['checks']` is empty and the plugin is not active, return only the static checks.
    * If `$_REQUEST['checks']` contains any runtime check and the plugin is not active, return an error as that check would be disallowed.
* For `plugin_check_run_checks`, please remember that this is not an endpoint to run multiple checks. Per #34, this is called `plugin_check_run_check` and should run a _single_ check.

cc @jjgrainger

**Comment by jjgrainger** [comment]
Thanks @felixarntz 

I've created the new issue to handle the get checks to run endpoint here https://github.com/10up/plugin-check/issues/90

As for `plugin_check_run_checks` I've checked over all related issues to ensure that we reference this as `plugin_check_run_check` (singular). I believe the AC's are clear that we are only ever running 1 check per request.

This is ready for you to review, let me know if you have any other feedback here. Thanks!

**Comment by felixarntz** [comment]
@jjgrainger The ACs here still refer to `run_checks` a few times - but let's not get caught up on that. :)

A few other notes though that maybe though are even related to that naming confusion:
* You say that the AJAX request should receive an "array containing a single check to be run". Why should this be an array if the AJAX action is for a single check? I would say it makes more sense for this to be just the check slug as a string.
* This part is also missing from the description of the `run_check` method, somehow this method needs to know which check to run.

We may want to discuss what the best approach here is. Maybe that's where I had a different understanding than you before, but now I'm questioning my own understanding here as well. From a pragmatic perspective, I think we should just have the `run_check` method that runs a single check, and then the parameter should probably be called `check` and be a string. _Or_ one could argue that, even though we only want to run a single check per request, we still call the method `run_checks` and add support so that it _could_ run multiple checks (i.e. the parameter would be a `checks` array). It seems more future proof, but it'll also be more work. WDYT?

**Comment by jjgrainger** [comment]
Thanks @felixarntz 

> You say that the AJAX request should receive an "array containing a single check to be run". Why should this be an array if the AJAX action is for a single check? I would say it makes more sense for this to be just the check slug as a string.

That's true, my thinking was (as you stated) to keep things plural despite the fact we are only ever running a single check for each request. The intention was this would be more future proof if we ever move forward with a way to run multiple checks in a single AJAX request.

For now, to keep things consistent I've updated the AC's to reflect the correct `run_check()` method to match the method name in other issues. I've also updated the AJAX request to send a string (to match the comma separated string the [AJAX_Runner](https://github.com/10up/plugin-check/blob/trunk/includes/Checker/AJAX_Runner.php#L83) expects).

If we decide to future proof this as part of the Milestone 1 Review we can make the updates then in a separate issue.

> This part is also missing from the description of the run_check method, somehow this method needs to know which check to run.

This is handled by the `AJAX_Runner` (and `Abstract_Check_Runner`) where we capture the plugin name and checks early in the request. The `AJAX_Runner` will throw an exception if either of these parameters are invalid. I've updated the AC's here to capture the exception thrown and return an error response. The `run()` method for the runner does not accept any parameters so I don't believe we need to process those here.

Let me know if you have any other feedback. Thanks!

**Comment by felixarntz** [comment]
@jjgrainger That sounds good and the ACs here look good as well so far, similar to my reply on #86 only pending small changes following the new issue about the runner class enhancements we discussed earlier in our call. For example, the AJAX action needs to get the runner from `Plugin_Request_Utility` or instantiate it itself if none was set. And in either case it then needs to set the plugin basename and the checks to run.

**Comment by jjgrainger** [comment]
Thanks @felixarntz 

I've updated the AC's with the points you've raised to include creating an instance of the `AJAX_Runner` if it's not already created and setting the check slugs and plugin parameters based on the methods created as part of #95 

Assigning back to you for approval.

**Comment by felixarntz** [comment]
@jjgrainger Pretty much the same reply as https://github.com/10up/plugin-check/issues/86#issuecomment-1450750316 applies here, just this one thing to be mindful of.

Also, I'm still a bit unclear on the AJAX action and parameter. In https://github.com/10up/plugin-check/issues/84#issuecomment-1446558785 you mention that you change it to single, but in that case we would also need to add support for a new `check` parameter to a few places, e.g. the `AJAX_Runner` class. That seems overly complicated, and your original thinking makes more sense to me than to introduce a new parameter. Like you're saying, even if we only want to run one check at a time, supporting multiple checks at a time is a good idea, and in this case it even makes the code simpler. So I'd say let's consistently go with the "support multiple checks" approach, i.e. name the AJAX action `run_checks` (plural) and use the `checks` parameter (array of strings).

**Comment by jjgrainger** [comment]
Thanks @felixarntz 

The updates I made were to align with names used with the ACs/PRs for other issues (e.g #34) without changing the functionality, thats to say even though the `run_check` method remains singular it could support multiple checks.

I can see however this could be confusing so I'm happy to go over the relevant issues/PRs to make the following changes if you agree?
- Update the `run_check` method in the `Admin_AJAX` to `run_checks`
- Update references to the `plugin_check_run_check` action to `plugin_check_run_checks`
- Update the `checks` key sent via the AJAX request to be an array of check slugs, instead of a comma separated string

Let me know if agree and I can make those changes.

**Comment by felixarntz** [comment]
@jjgrainger Thanks, that sounds right. However, no need to update the names on every other issue since it's a bit of a maintenance burden. Of course if it's fast feel free to do so :)

**Comment by jjgrainger** [comment]
Thanks @felixarntz I've updated the AC's here to reflect those changes but won't update the other issues. I'll address these changes in the PR's as and when they arrive.

Moving this to todo. Thanks!
