### ISSUE TITLE
CLI Runtime Environment Setup/Cleanup

### ISSUE THREAD

**Issue by jjgrainger** [10up/plugin-check#87]
This issue will implement the runtime environment setup and cleanup for CLI requests. This will utilise the `Runtime_Environment_Setup` class to setup the WP environment before checks are run, and cleanup the environment once all checks are complete.

## Acceptance Criteria

- Add a new `before_wp_load` hook with `WP_CLI::add_hook()` to implement the object-cache.php drop-in file.
    - The hook will manually (not using the WP filesystem) add the object-cache.php drop-in file to the wp-content folder.
- Create a `cli.php` file in the plugin root.
    - This file will be used to setup the `Plugin_Check_Command` both early and late in the WordPress load process.
    - The file will first check if the `Plugin_Check_Command` class exists.
        - If it does not this file is running before WordPress has loaded and the command will need to be setup manually.
            - This is done by loading the plugin autoload file so the class is available.
            - A new `Plugin_Context` for the plugin checker is created and passed to the `Plugin_Check_Command` constructor.
            - The `Plugin_Check_Command` is then registered to the WordPress CLI.
        - If the `Plugin_Check_Command` class does exist.
             - A check is made to see if the `$context` variable exists, which will be set in the `Plugin_Main::add_hooks()` method.
             - A new instance of the `Plugin_Check_Command` is created passing the `$context` to the constructor.
             - The `Plugin_Check_Command` is then registered to the WordPress CLI.
- Update the `Plugin_Main::add_hooks()` method to `require_once` the `cli.php` file, instead of adding the command directly to WP_CLI.
- Update the `wp plugin check` to run the `Runtime_Environment_Setup::setup()` method at the start of the commands run process if any runtime check is to be performed. This is to setup the database tables required for runtime checks.
- Update the `wp plugin check` to run the `Runtime_Environment_Setup::cleanup()` method at the end of the commands run process. This will remove the database tables and object-cache.php drop-in file if they exists.
- When running the `wp plugin check` command the `--require` flag can be used to include the `cli.php` file early to create the object-cache.php file and register the command.

**Comment by felixarntz** [comment]
@jjgrainger I think implementing this will be more complicated than we thought. We should probably think and discuss further how to do this. Some early feedback here:
> This method will get an instance of the `CLI_Runner` class via the `Plugin_Request_Utility::get_runner()` method

This won't work since before WP is loaded, no runner will have been initialized. We may need to determine whether a runtime check is being used separately without the runner class, or we need to rethink how those runner classes work because normally it would only get initialized from the `object-cache.php`. But that would only get placed by the `Runtime_Environment_Setup`. 🤔 

The runner infrastructure really seems to be the most complicated part of this architecture to figure out 😄 

> Update the `Plugin_Check_Command` class so it can be required in to WP CLI at the earliest point

One of the things that this will involve is that the actual addition of the command to `WP_CLI` needs to somehow be included in the file that is required early. But then we also have to remember that in that case autoloading is not set up yet, since all this would happen even before WordPress is loaded, let alone the plugin checker.

One idea I have would be to add a new file e.g. `cli.php` in the plugin root directory and have _that_ be the file that needs to be required early. In that file we could include a check like "if plugin check command class does not exist, load the autoload file". Then, we would need to set up the `Plugin_Context` correctly based on the main file and the `Plugin_Check_Command` instance. We could then `require_once` this file in the `Plugin_Main::add_hooks()` method instead of having the code to add the command there. We have to consider that it needs to work in both ways, whether the `--require` option of WP-CLI is used or not.

**Comment by felixarntz** [comment]
@jjgrainger ACs LGTM! The only thing missing is to also conditionally call the preparation logic from `Runtime_Environment_Setup` in the beginning of the CLI command, since that'll still be needed to set up the DB tables (of course only relevant if any runtime check should be performed).

**Comment by jjgrainger** [comment]
Thanks @felixarntz I've updated the AC's with the `Runtime_Environment_Setup` to run at the start of the command process. I'll move this to todo as you've approved the rest of the AC's.
