### ISSUE TITLE
Create abstract class Runtime_Check

### ISSUE THREAD

**Issue by mehulkaklotar** [10up/plugin-check#9]
This abstract class will be used to create concrete checks that perform runtime analysis. These checks will run elements of the plugin code on the server to test its behavior against an expected outcome.

## Acceptance Criteria

- An abstract `Abstract_Runtime_Check` class exists
- The `Abstract_Runtime_Check` class implements the `Check` and `Preparation` interfaces
- The class contains an abstract `prepare` method
    - This method will return a `Callable` which is the cleanup function for the preparations run
    - This method can throw and `Exception` when the preparation fails
 - The class will contain an abstract `run` method
     - The method accepts a single `$results` parameter, which is an instance of `Check_Result`
     - The method can throw and `Exception` on critical failure unrelated to check errors or warnings
     - The method does not return anything

**Comment by felixarntz** [comment]
@jjgrainger I think the ACs here are based on my `Abstract_**Request**_Check` implementation (https://github.com/felixarntz/plugin-check/blob/main/includes/Checker/Checks/Abstract_Request_Check.php), but then turn it into `Abstract_Runtime_Check`. We should have an `Abstract_Runtime_Check` class, but it should only include what is needed for _any_ runtime check. In the ACs here you're including things though that would only be relevant for runtime checks that mock requests to a certain URL, which not every runtime check will have to do.

Let's think a bit more about this. What logic would make sense to be in a base class for a runtime check because it would be used in _every_ runtime check? Maybe there are some things, or maybe there are none, in which case this could just be an empty class for now. I'd argue the only thing we need for sure here is implementing also the `Preparation` interface, since every runtime check will require some sort of preparation and cleanup.

Overall, I wonder whether for more specific things (like mocking a request, or backing up and restoring globals, or backing up and restoring filters) we should eventually implement PHP traits that the individual runtime check classes can use as needed.

Last but not least: This mentions the `Preparation` interface, however that is only added in #16. Please clarify the intended sequence of those 2 issues, should this interface just be scaffolded here, or will #16 be implemented first? Cross-referencing the other issue would be useful for such cases.

**Comment by jjgrainger** [comment]
Thanks @felixarntz 

I agree and after reviewing this I've left the implementation for this issue very basic. I've only defined the 2 abstract methods any runtime check would need (`run` and `prepare`) for now. We can always review later if we discover from some of the Check implementations if there are other common functionality that would be better in this abstract class.

Alternatively, we may discover that this functionality would be better suited in traits as you have said in your feedback on the AC's. With that in mind I will create a new issue for a trait that contains some of the Request Check functionality removed from this class.
