### ISSUE TITLE
Update Runner Classes to accept and validate the checks to run and plugin file

### ISSUE THREAD

**Issue by jjgrainger** [10up/plugin-check#93]
Currently, the `AJAX_Runner` and `CLI_Runner` classes determine the checks to run and the plugin to check early in the WordPress load process. In doing so, these parameters are not collected or validated via the standard WordPress functions available. This issue looks to update both runners to handle these variables via WordPress functions, such as the process request `$args` in the CLI. 

## Acceptance Criteria

- Update the `Abstract_Check_Runner` with the following:
    - Add a constructor used to determine if the class was instantiated early. This is done by checking the `did_action( 'muplugins_loaded' )` - If the MU Plugins have not been loaded yet, the runner was initialized early. This boolean value should be stored in a class property to be used later.
    - A new public `set_check_slugs_to_run( array $check_slugs )` method is created. This accepts an array of check slugs to run that will be manually set during the AJAX/CLI requests. The value passed in stored as a class property to be used later.
    - A new public `set_plugin_basename( string $plugin_basename )` method is created. This accepts the plugin basename to be checked and will be manually set during the AJAX/CLI requests. The value passed in stored as a class property to be used later.
    - Add a protected `get_checks_instance()` method. This method will replace the abstract methods created in the AJAX/CLI runner classes. This method will check if the class was initialized early and if the plugin basename was set manually. If both are true, the class will compare the plugin basename passed with those determined by the request (`determine_plugin_basename()`). If the set values do not match the computed values an exception is thrown. If the values match, the Check instance is created using the plugin basename.
    - Add a protected `get_check_slugs_to_run()` method. This method will replace the abstract methods created in the AJAX/CLI runner classes. This method will check if the class was initialized early and if the check slugs array was set manually. If both are true, the class will compare the checks passed with those determined by the request (`determine_check_slugs_to_run ()`). If the values do not match an exception is thrown. If the values match, the array of check slugs is returned.
    - Rename the abstract `get_checks_instance()` method to `determine_plugin_basename()`
    - Rename the abstract `get_check_slugs_to_run()` method to `determine_check_slugs_to_run()`
- Update the `AJAX_Runner` class with the following:
    - Remove the `get_checks_instance()` method
    - Rename the `get_check_slugs_to_run()` method to `determine_check_slugs_to_run()`
    - Add a protected `determine_plugin_basename()` method. This method will return the basename of the plugin based on the AJAX request sent.
- Update the `CLI_Runner` class with the following:
    - Remove the `get_checks_instance()` method
    - Rename the `get_check_slugs_to_run()` method to `determine_check_slugs_to_run()`
    - Add a protected `determine_plugin_basename()` method. This method will return the basename of the plugin based on the arguments passed in the CLI command.

## Test Coverage
- Add unit tests for the `AJAX_Runner`:
    - Test an exception is thrown when the plugin basename in the request does not match the manually set plugin basename.
    - Test an exception is thrown when the check slugs array in the request does not match the manually set array of check slug.
- Add unit tests for the `CLI_Runner`:
    - Test an exception is thrown when the plugin basename in the cli args does not match the manually set plugin basename.
    - Test an exception is thrown when the check slugs array in the cli args does not match the manually set array of check slug.

**Comment by felixarntz** [comment]
@jjgrainger Some feedback on the ACs:
* Do we really need the `$early` parameter? I would think we can add simple logic into the base runner class constructor to determine that automatically, for example by consider early as `! did_action( 'muplugins_loaded' )`. We could set this value as a class property when the constructor of the runner class is called.
* For the `Plugin_Request_Utility` class, I don't think it requires that `$early` awareness overall. Isn't it sufficient to have that in the runner classes?
* The new validation logic I think should be part of the respective new `set_*()` method so that the comparison with the computed parameter happens as early as a new value is being set in an "attempt" to override the computed values. If they're not equal, an exception can be thrown from the setter.
* It may be worth noting that we should probably also rename the protected abstract methods in the runner classes to maybe `determine_*()` rather than `get_*()`, since we need to have the logic for the new parameter overrides in the base class. For example `get_checks_to_run()` could be a protected method that uses the set value (if one is set), or if none is set calls `determine_checks_to_run()` which is implemented by the child class.

**Comment by jjgrainger** [comment]
Thanks @felixarntz I've updated the AC's based on your feedback. PR is created here also #95

**Comment by felixarntz** [comment]
@jjgrainger ACs here look right, except for a few renaming things now that the PR is there, but let's just ignore that and proceed with the PR. FWIW I would also not have caught those things without having reviewed the PR.
